"""Added is_verified, state and lga columns

Revision ID: a71a836fed51
Revises: 13a733f64574
Create Date: 2024-01-25 05:56:44.084565

"""
#pylint: disable=E0401, E1101, C0116, C0103
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a71a836fed51'
down_revision: Union[str, None] = '13a733f64574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('lga', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lga')
    op.drop_column('users', 'state')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
